### ISSUE TITLE
Understanding of 'diff' in code

### ISSUE THREAD

**Issue by lxn96** [facebookresearch/Adversarial-Continual-Learning#10]
Hi, thanks for openning ACL codes. I see that there is a parameter ‘diff’ in config file. And in discriminator.py, if args.diff =='yes', there will have GradientReversal in discriminator,  otherwise there is no. However, in acl.py, the arg.diff is used to choose whether to use diff_loss. I think the GradientReversal is used for adv_loss of adversarial training, regardless of whether diff loss is used or not. Can you solve my doubts? Thank you!

**Comment by SaynaEbrahimi** [comment]
Hi, thanks for your interest! You're right I should have named them better to be clear. In my experiment with diff loss I got slightly better overall results when gradient reversal was used in the discriminator. So I used the same flag for both so that when I had diff loss on, I was using grad reversal as well. But conceptually, they are not related.

**Comment by lxn96** [comment]
So, if I don't use diff loss, should I use gradient reversal in the discriminator?

**Comment by SaynaEbrahimi** [comment]
Feel free to try. For me it happened to cause a slight decrease, but like I said, they are not related and contribute to the total loss in their own way.
